In [1]:
# Import torch and other required modules
import torch
import numpy as np

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,4,5,6)
print(f'a: {type(a)}, {a.dtype}')
print('a: {}, {}'.format(type(a), a.dtype))
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=100, size=(5,5))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


In [14]:
#Function1 -- torch.squeeze()
np.random.seed(1)
a = np.random.randint(low=0, high=100, size=(1,5,5))
print(f'a: {type(a)}, {a.dtype}')
print(a)
print('------------------------------')

b = torch.from_numpy(a) #Change to a tensor from a numpy array
b2 = torch.squeeze(b) #Returns a tensor with all the dimensions of input of size 1 removed.
print(f'b2: {type(b2)}, {b2.size()}, {b2.dtype}') #1*5*5 --> 5*5
print(b2)



a: <class 'numpy.ndarray'>, int64
[[[37 12 72  9 75]
  [ 5 79 64 16  1]
  [76 71  6 25 50]
  [20 18 84 11 28]
  [29 14 50 68 87]]]
------------------------------
b2: <class 'torch.Tensor'>, torch.Size([5, 5]), torch.int64
tensor([[37, 12, 72,  9, 75],
        [ 5, 79, 64, 16,  1],
        [76, 71,  6, 25, 50],
        [20, 18, 84, 11, 28],
        [29, 14, 50, 68, 87]])


In [16]:
#Function2 -- torch.unsqueeze()
np.random.seed(2)
a = np.random.randint(low=0, high=100, size=(1,5,5))
print(f'a: {type(a)}, {a.dtype}')
print(a)
print('------------------------------')

b = torch.from_numpy(a) #change to a tensor from a numpy array
b2 = torch.unsqueeze(b,0) #Returns a new tensor with a dimension of size one inserted at the position 0
print(f'b2: {type(b2)}, {b2.size()}, {b2.dtype}') #1*5*5 --> 1*1*5*5
print(b2)

b3 = torch.unsqueeze(b,2) #Returns a new tensor with a dimension of size one inserted at the position 2
print(f'b3: {type(b3)}, {b3.size()}, {b3.dtype}') #1*5*5 --> 1*5*1*5
print(b2)

a: <class 'numpy.ndarray'>, int64
[[[40 15 72 22 43]
  [82 75  7 34 49]
  [95 75 85 47 63]
  [31 90 20 37 39]
  [67  4 42 51 38]]]
------------------------------
b2: <class 'torch.Tensor'>, torch.Size([1, 1, 5, 5]), torch.int64
tensor([[[[40, 15, 72, 22, 43],
          [82, 75,  7, 34, 49],
          [95, 75, 85, 47, 63],
          [31, 90, 20, 37, 39],
          [67,  4, 42, 51, 38]]]])
b3: <class 'torch.Tensor'>, torch.Size([1, 5, 1, 5]), torch.int64
tensor([[[[40, 15, 72, 22, 43],
          [82, 75,  7, 34, 49],
          [95, 75, 85, 47, 63],
          [31, 90, 20, 37, 39],
          [67,  4, 42, 51, 38]]]])


In [28]:
#Function3 -- torch.vstack()
np.random.seed(2)
a = np.random.randint(low=0, high=100, size=(1,4,5))
print(f'a: {type(a)}, {a.dtype}')
print(a)

b = np.random.randint(low=0, high=100, size=(1,4,5))
print(f'a: {type(b)}, {b.dtype}')
print(b)

c = torch.from_numpy(a) #Change a to a tensor from a numpy array
d = torch.from_numpy(b) #Change b to a tensor from a numpy array
e = torch.vstack((c,d)) #Stack tensors in sequence vertically (row wise)
print(f'e: {type(e)}, {e.size()}, {e.dtype}') # 2*4*5
print(e)
print('----------------------------------------------------')
try:
  np.random.seed(3)
  a2 = np.random.randint(low=0, high=100, size=(1,4,5))
  b2 = np.random.randint(low=0, high=100, size=(1,3,5))

  c2 = torch.from_numpy(a2) #Change a to a tensor from a numpy array  
  d2 = torch.from_numpy(b2) #Change b to a tensor from a numpy array
  e2 = torch.vstack((c2,d2)) #Stack tensors in sequence vertically (row wise)
  print(f'e2: {type(e2)}, {e2.size()}, {e2.dtype}') 
  print(e2)
except:
  print('something wrong') # dimension of c2 and d2 are not match



a: <class 'numpy.ndarray'>, int64
[[[40 15 72 22 43]
  [82 75  7 34 49]
  [95 75 85 47 63]
  [31 90 20 37 39]]]
a: <class 'numpy.ndarray'>, int64
[[[67  4 42 51 38]
  [33 58 67 69 88]
  [68 46 70 95 83]
  [31 66 80 52 76]]]
e: <class 'torch.Tensor'>, torch.Size([2, 4, 5]), torch.int64
tensor([[[40, 15, 72, 22, 43],
         [82, 75,  7, 34, 49],
         [95, 75, 85, 47, 63],
         [31, 90, 20, 37, 39]],

        [[67,  4, 42, 51, 38],
         [33, 58, 67, 69, 88],
         [68, 46, 70, 95, 83],
         [31, 66, 80, 52, 76]]])
----------------------------------------------------
something wrong


In [34]:
#Function4 -- torch.arange
torch.arange(0,6,2) # (start,end step)

tensor([0, 2, 4])